version: '3'
services:
  docker-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db_sales
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres